apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres        
    spec:
      containers:
        - name: postgres
          image: postgres:14.4
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_USER
            value: "kubenews"
          - name: POSTGRES_DB
            value: "kubenews"
          - name: POSTGRES_PASSWORD
            value: "Pg#123"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-news-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: rleafar/kube-news:v1
          ports:
            - containerPort: 8080
          env:
          - name: DB_USERNAME
            value: "kubenews"
          - name: DB_DATABASE
            value: "kubenews"
          - name: DB_PASSWORD
            value: "Pg#123"
          - name: DB_HOST
            value: "postgres"
---

apiVersion: v1
kind: Service
metadata:
  name: service-web
spec:
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30000
    targetPort: 8080
  type: NodePort